MAKE_POST_QUERY = """INSERT INTO `SIBMPostData` (post_uuid, post_content, post_score, username) VALUES ("{uid}", "{cont}", {score}, "{user}")"""
SELECT_POST_QUERY = """SELECT * FROM `SIBMPostData` ORDER BY post_score DESC, post_timestamp DESC LIMIT 25;"""
REGISTER_USER_QUERY = """INSERT INTO `SIBMUsers` (username, passwd) VALUES ("{u}", "{p}");"""
VERIFY_USER_QUERY = """SELECT passwd FROM `SIBMUsers` WHERE username="{}";"""
GET_POST_QUERY = """SELECT * FROM `SIBMPostData` WHERE post_uuid = ('{guid}');"""
UPDATE_POST_SCORE_QUERY = """UPDATE `SIBMPostData` SET post_score={score} WHERE post_uuid="{uid}";"""
CHECK_USER_VOTE_QUERY = """SELECT vote_type FROM `SIBMUserVotes` WHERE (username="{user}" AND post_uuid="{guid}");"""
UPDATE_VOTE_TABLE_QUERY = """INSERT INTO `SIBMUserVotes` (username, post_uuid, vote_type) VALUES ("{user}", "{guid}", "{vote}");"""
CHANGE_VOTE_TABLE_QUERY = """UPDATE `SIBMUserVotes` SET vote_type="{vote}" WHERE username="{user}" AND post_uuid="{guid}";"""